export enum Permission {
    MANAGE_DASHBOARD = 'MANAGE_DASHBOARD',
    MANAGE_WAREHOUSE = 'MANAGE_WAREHOUSE',
    MANAGE_CONTENT = 'MANAGE_CONTENT',
    MANAGE_ACCOUNT = 'MANAGE_ACCOUNT',
    MANAGE_SALES = 'MANAGE_SALES',
    MANAGE_EMPLOYEE = 'MANAGE_EMPLOYEE',
}
